install: yarn install
script:
  - yarn lint
  - yarn test
  - yarn docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/.vuepress/dist
  on:
    branch: master
    commit_message: /^v?\d+\.\d+\.\d+/
